 export const LangAuthor = [
     {
     FaceName:"Tamil",    
     TempName:"Tamil",    
     TempSearchName:"searchTamil",    
     searchTamil:true,
},
    {
    FaceName:"Telugu",    
    TempName:"Telugu",    
    TempSearchName:"searchTelugu",    
    searchTelugu:true,
},
    {
    FaceName:"Gujarati",    
    TempName:"Gujarati",    
    TempSearchName:"searchGujarati",    
    searchGujarati:true,
},
    {
    FaceName:"Marathi",    
    TempName:"Marathi",    
    TempSearchName:"searchMarathi",    
    searchMarathi:true,
},
    {
    FaceName:"Malayalam",    
    TempName:"Malayalam",    
    TempSearchName:"searchMalayalam",    
    searchMalayalam:true,
},
    {
    FaceName:"Odia",    
    TempName:"Odia",    
    TempSearchName:"searchOdia",    
    searchOdia:true,
},
    {
    FaceName:"Assamesse",    
    TempName:"Assamesse",    
    TempSearchName:"searchAssamesse",    
    searchAssamesse:true,
},
    {
    FaceName:"Kannada",    
    TempName:"Kannada",    
    TempSearchName:"searchKannada",    
    searchKannada:true,
},
    {
    FaceName:"Bengali",    
    TempName:"Bengali",    
    TempSearchName:"searchBengali",    
    searchBengali:true,
},
    {
    FaceName:"Urdu",    
    TempName:"Urdu",    
    TempSearchName:"searchUrdu",    
    searchUrdu:true,
}

 ]
 export const AuthorMains = [
     {
         FaceName:"Astro Mragaank",    
         TempName:"Mragaank",    
         TempSearchName:"searchMragaank",    
         searchTamil:true,
},
     {
     FaceName:"Astro Hariharan",    
     TempName:"Hariharan",    
     TempSearchName:"searchHariharan",    
     searchTamil:true,
}
 ]